#!/bin/bash



# remove previous backup file, since we are using hard links the file
# must not be changed, else we'd be changing the previous backups
[[ -f ${RS}_mysqldump.sql.bz2 ]] && rm ${RS}_mysqldump.sql.bz2

# do the backup
doDbBk > ${RS}_mysqldump.sql.bz2
