#!/bin/bash
#--
# This script loads configurations form the main CONFig file and starts
# the "replicator" that will replicate the previous backup and call the
# worker scripts the will do the actual backup.
#--
# Project: https://github.com/jfig/rsync-backups/
# License: https://github.com/jfig/rsync-backups/blob/master/LICENSE
#----

export RSYNCBACKUPS_LIBDIR="/usr/local/lib/rsync-backups/"
export CONFIG_DIR="/etc/rsync-backups/"

BKSCRIPT=${RSYNCBACKUPS_LIBDIR}"/replicator"

#-- pre-flight testing

. ${CONFIG_DIR}/conf  || { >&2 echo "fatal: could not load config"; exit 1; }
[ -f $BKSCRIPT ] || { >&2 echo "fatal: could not find $BKSCRIPT"; exit 2; }
[ -x $BKSCRIPT ] || { >&2 echo "fatal: $BKSCRIPT is not an executable"; exit 3; }

#-- flight

$BKSCRIPT -d $BKDIR -t $DURATION
